// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtsfsdhbfnbvktmlgqnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0c2ZzZGhiZm5idmt0bWxncW53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjcxMTcsImV4cCI6MjA2Mzk0MzExN30.6oZtK-SkSuoKt93cMRSfufCkV1ZiOa5g1JhZrqe3cvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);